/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_validator_free(a: number): void;
export function validator_from_str(a: number, b: number): number;
export function validator_from_str_cjfeature(a: number, b: number, c: number, d: number): void;
export function validator_get_status(a: number): number;
export function validator_get_errors_string(a: number): number;
export function validator_get_input_cityjson_version(a: number): number;
export function validator_get_cityjson_schema_version(a: number): number;
export function validator_is_cityjsonfeature(a: number): number;
export function validator_get_extensions_urls(a: number): number;
export function validator_validate(a: number): void;
export function validator_number_extensions(a: number): number;
export function validator_add_one_extension_from_str(a: number, b: number, c: number, d: number, e: number): number;
export function validator_json_syntax(a: number, b: number): void;
export function validator_schema(a: number, b: number): void;
export function validator_extensions(a: number, b: number): void;
export function validator_parents_children_consistency(a: number, b: number): void;
export function validator_wrong_vertex_index(a: number, b: number): void;
export function validator_semantics_arrays(a: number, b: number): void;
export function validator_materials(a: number, b: number): void;
export function validator_textures(a: number, b: number): void;
export function validator_duplicate_vertices(a: number, b: number): void;
export function validator_extra_root_properties(a: number, b: number): void;
export function validator_unused_vertices(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
